---
steps:

- name: "gcr.io/cloud-builders/docker"
  id: build
  args:
  - "build"
  - "-t"
  - "gcr.io/$PROJECT_ID/natsbox:$SHORT_SHA"
  - "."

- name: "gcr.io/cloud-builders/docker"
  id: tag
  waitFor:
  - build
  args:
  - "tag"
  - "gcr.io/$PROJECT_ID/natsbox:$SHORT_SHA"
  - "gcr.io/$PROJECT_ID/natsbox:latest"

images:
  - "gcr.io/$PROJECT_ID/natsbox:$SHORT_SHA"
  - "gcr.io/$PROJECT_ID/natsbox:latest"
